convert -resize 30% _assets/images/ali-pollo-marinate.jpg assets/images/ali-pollo-marinate.jpg
convert -resize 30% _assets/images/ali-pollo-marinate-2.jpg assets/images/ali-pollo-marinate-2.jpg
convert -resize 30% _assets/images/pulled-pork.jpg assets/images/pulled-pork.jpg
convert -resize 30% _assets/images/pollo-lattina-birra.jpg assets/images/pollo-lattina-birra.jpg
convert -resize 30% _assets/images/pulled-pork-2.jpg assets/images/pulled-pork-2.jpg
convert -resize 30% _assets/images/costine.jpg assets/images/costine.jpg
convert -resize 30% _assets/images/burger-buns-2.jpg assets/images/burger-buns-2.jpg
convert -resize 30% _assets/images/rub-1.jpg assets/images/rub-1.jpg
convert -resize 30% _assets/images/burger-buns.jpg assets/images/burger-buns.jpg
convert -resize 30% _assets/images/costine-2.jpg assets/images/costine-2.jpg
convert -resize 30% _assets/images/costine-3.jpg assets/images/costine-3.jpg
